AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGatewayApiAssigment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: 
              Fn::Sub: 'https://${ServerlessDeploymentBucket}.s3.${AWS::Region}.amazonaws.com/api-definition.yml'

  StoreDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/store-data.storeDataHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30

  MyLambdaPermissionAssigment:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt StoreDataFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayApiAssigment}/*/*"

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Dev stage"
    Value: !Sub "https://#{ApiGatewayApiAssigment}.execute-api.${AWS::Region}.amazonaws.com/Dev/"
